export enum Champion {
  NONE = -1,
  ANNIE = 1,
  AHRI = 103,
  AKALI = 84,
  AKSHAN = 166,
  ALISTAR = 12,
  AMUMU = 32,
  ANIVIA = 34,
  APHELIOS = 523,
  ASHE = 22,
  AURELIONSOL = 136,
  AZIR = 268,
  BARD = 432,
  BELVETH = 200,
  BLITZCRANK = 53,
  BRAND = 63,
  BRAUM = 201,
  CAITLYN = 51,
  CAMILLE = 164,
  CASSIOPEIA = 69,
  CHOGATH = 31,
  CORKI = 42,
  DARIUS = 122,
  DIANA = 131,
  DRAVEN = 119,
  DRMUNDO = 36,
  EKKO = 245,
  ELISE = 60,
  EVELYNN = 28,
  EZREAL = 81,
  FIDDLESTICKS = 9,
  FIORA = 114,
  FIZZ = 105,
  GALIO = 3,
  GANGPLANK = 41,
  GAREN = 86,
  GNAR = 150,
  GRAGAS = 79,
  GRAVES = 104,
  GWEN = 887,
  HECARIM = 120,
  HEIMERDINGER = 74,
  ILLAOI = 420,
  IRELIA = 39,
  IVERN = 427,
  JANNA = 40,
  JARVANIV = 59,
  JAX = 24,
  JAYCE = 126,
  JHIN = 202,
  JINX = 222,
  KAISA = 145,
  KALISTA = 429,
  KARMA = 43,
  KARTHUS = 30,
  KASSADIN = 38,
  KATARINA = 55,
  KAYLE = 10,
  KAYN = 141,
  KENNEN = 85,
  KHAZIX = 121,
  KINDRED = 203,
  KLED = 240,
  KOGMAW = 96,
  KSANTE = 897,
  LEBLANC = 7,
  LEESIN = 64,
  LEONA = 89,
  LILLIA = 876,
  LISSANDRA = 127,
  LUCIAN = 236,
  LULU = 117,
  LUX = 99,
  MALPHITE = 54,
  MALZAHAR = 90,
  MAOKAI = 57,
  MASTERYI = 11,
  MISSFORTUNE = 21,
  MONKEYKING = 62,
  MORDEKAISER = 82,
  MORGANA = 25,
  NAMI = 267,
  NASUS = 75,
  NAUTILUS = 111,
  NEEKO = 518,
  NIDALEE = 76,
  NILAH = 895,
  NOCTURNE = 56,
  NUNU = 20,
  OLAF = 2,
  ORIANNA = 61,
  ORNN = 516,
  PANTHEON = 80,
  POPPY = 78,
  PYKE = 555,
  QIYANA = 246,
  QUINN = 133,
  RAKAN = 497,
  RAMMUS = 33,
  REKSAI = 421,
  RELL = 526,
  RENATAGLASC = 888,
  RENEKTON = 58,
  RENGAR = 107,
  RIVEN = 92,
  RUMBLE = 68,
  RYZE = 13,
  SAMIRA = 360,
  SEJUANI = 113,
  SENNA = 235,
  SERAPHINE = 147,
  SETT = 875,
  SHACO = 35,
  SHEN = 98,
  SHYVANA = 102,
  SINGED = 27,
  SION = 14,
  SIVIR = 15,
  SKARNER = 72,
  SONA = 37,
  SORAKA = 16,
  SWAIN = 50,
  SYLAS = 517,
  SYNDRA = 134,
  TAHMKENCH = 223,
  TALIYAH = 163,
  TALON = 91,
  TARIC = 44,
  TEEMO = 17,
  THRESH = 412,
  TRISTANA = 18,
  TRUNDLE = 48,
  TRYNDAMERE = 23,
  TWISTEDFATE = 4,
  TWITCH = 29,
  UDYR = 77,
  URGOT = 6,
  VARUS = 110,
  VAYNE = 67,
  VEIGAR = 45,
  VELKOZ = 161,
  VEX = 711,
  VI = 254,
  VIEGO = 234,
  VIKTOR = 112,
  VLADIMIR = 8,
  VOLIBEAR = 106,
  WARWICK = 19,
  XAYAH = 498,
  XERATH = 101,
  XINZHAO = 5,
  YASUO = 157,
  YONE = 777,
  YORICK = 83,
  YUUMI = 350,
  ZAC = 154,
  ZED = 238,
  ZERI = 221,
  ZIGGS = 115,
  ZILEAN = 26,
  ZOE = 142,
  ZYRA = 143,
}

export const ChampionName = {
  [Champion.NONE]: "None",
  [Champion.ANNIE]: "Annie",
  [Champion.AHRI]: "Ahri",
  [Champion.AKALI]: "Akali",
  [Champion.AKSHAN]: "Akshan",
  [Champion.ALISTAR]: "Alistar",
  [Champion.AMUMU]: "Amumu",
  [Champion.ANIVIA]: "Anivia",
  [Champion.APHELIOS]: "Aphelios",
  [Champion.ASHE]: "Ashe",
  [Champion.AURELIONSOL]: "Aurelion Sol",
  [Champion.AZIR]: "Azir",
  [Champion.BARD]: "Bard",
  [Champion.BELVETH]: "Belveth",
  [Champion.BLITZCRANK]: "Blitzcrank",
  [Champion.BRAND]: "Brand",
  [Champion.BRAUM]: "Braum",
  [Champion.CAITLYN]: "Caitlyn",
  [Champion.CAMILLE]: "Camille",
  [Champion.CASSIOPEIA]: "Cassiopeia",
  [Champion.CHOGATH]: "Cho'Gath",
  [Champion.CORKI]: "Corki",
  [Champion.DARIUS]: "Darius",
  [Champion.DIANA]: "Diana",
  [Champion.DRAVEN]: "Draven",
  [Champion.DRMUNDO]: "Dr. Mundo",
  [Champion.EKKO]: "Ekko",
  [Champion.ELISE]: "Elise",
  [Champion.EVELYNN]: "Evelynn",
  [Champion.EZREAL]: "Ezreal",
  [Champion.FIDDLESTICKS]: "Fiddlesticks",
  [Champion.FIORA]: "Fiora",
  [Champion.FIZZ]: "Fizz",
  [Champion.GALIO]: "Galio",
  [Champion.GANGPLANK]: "Gangplank",
  [Champion.GAREN]: "Garen",
  [Champion.GNAR]: "Gnar",
  [Champion.GRAGAS]: "Gragas",
  [Champion.GRAVES]: "Graves",
  [Champion.GWEN]: "Gwen",
  [Champion.HECARIM]: "Hecarim",
  [Champion.HEIMERDINGER]: "Heimerdinger",
  [Champion.ILLAOI]: "Illaoi",
  [Champion.IRELIA]: "Irelia",
  [Champion.IVERN]: "Ivern",
  [Champion.JANNA]: "Janna",
  [Champion.JARVANIV]: "Jarvan IV",
  [Champion.JAX]: "Jax",
  [Champion.JAYCE]: "Jayce",
  [Champion.JHIN]: "Jhin",
  [Champion.JINX]: "Jinx",
  [Champion.KAISA]: "Kai'Sa",
  [Champion.KALISTA]: "Kalista",
  [Champion.KARMA]: "Karma",
  [Champion.KARTHUS]: "Karthus",
  [Champion.KASSADIN]: "Kassadin",
  [Champion.KATARINA]: "Katarina",
  [Champion.KAYLE]: "Kayle",
  [Champion.KAYN]: "Kayn",
  [Champion.KENNEN]: "Kennen",
  [Champion.KHAZIX]: "Kha'Zix",
  [Champion.KINDRED]: "Kindred",
  [Champion.KLED]: "Kled",
  [Champion.KOGMAW]: "Kog'Maw",
  [Champion.KSANTE]: "K-Sante",
  [Champion.LEBLANC]: "LeBlanc",
  [Champion.LEESIN]: "Lee Sin",
  [Champion.LEONA]: "Leona",
  [Champion.LILLIA]: "Lillia",
  [Champion.LISSANDRA]: "Lissandra",
  [Champion.LUCIAN]: "Lucian",
  [Champion.LULU]: "Lulu",
  [Champion.LUX]: "Lux",
  [Champion.MALPHITE]: "Malphite",
  [Champion.MALZAHAR]: "Malzahar",
  [Champion.MAOKAI]: "Maokai",
  [Champion.MASTERYI]: "Master Yi",
  [Champion.MISSFORTUNE]: "Miss Fortune",
  [Champion.MONKEYKING]: "Wukong",
  [Champion.MORDEKAISER]: "Mordekaiser",
  [Champion.MORGANA]: "Morgana",
  [Champion.NAMI]: "Nami",
  [Champion.NASUS]: "Nasus",
  [Champion.NAUTILUS]: "Nautilus",
  [Champion.NEEKO]: "Neeko",
  [Champion.NIDALEE]: "Nidalee",
  [Champion.NILAH]: "Nilah",
  [Champion.NOCTURNE]: "Nocturne",
  [Champion.NUNU]: "Nunu & Willump",
  [Champion.OLAF]: "Olaf",
  [Champion.ORIANNA]: "Orianna",
  [Champion.ORNN]: "Ornn",
  [Champion.PANTHEON]: "Pantheon",
  [Champion.POPPY]: "Poppy",
  [Champion.PYKE]: "Pyke",
  [Champion.QIYANA]: "Qiyana",
  [Champion.QUINN]: "Quinn",
  [Champion.RAKAN]: "Rakan",
  [Champion.RAMMUS]: "Rammus",
  [Champion.REKSAI]: "Rek'Sai",
  [Champion.RELL]: "Rell",
  [Champion.RENATAGLASC]: "Renekton",
  [Champion.RENEKTON]: "Renekton",
  [Champion.RENGAR]: "Rengar",
  [Champion.RIVEN]: "Riven",
  [Champion.RUMBLE]: "Rumble",
  [Champion.RYZE]: "Ryze",
  [Champion.SAMIRA]: "Samira",
  [Champion.SEJUANI]: "Sejuani",
  [Champion.SENNA]: "Senna",
  [Champion.SERAPHINE]: "Seraphine",
  [Champion.SETT]: "Sett",
  [Champion.SHACO]: "Shaco",
  [Champion.SHEN]: "Shen",
  [Champion.SHYVANA]: "Shyvana",
  [Champion.SINGED]: "Singed",
  [Champion.SION]: "Sion",
  [Champion.SIVIR]: "Sivir",
  [Champion.SKARNER]: "Skarner",
  [Champion.SONA]: "Sona",
  [Champion.SORAKA]: "Soraka",
  [Champion.SWAIN]: "Swain",
  [Champion.SYLAS]: "Sylas",
  [Champion.SYNDRA]: "Syndra",
  [Champion.TAHMKENCH]: "Tahm Kench",
  [Champion.TALIYAH]: "Taliyah",
  [Champion.TALON]: "Talon",
  [Champion.TARIC]: "Taric",
  [Champion.TEEMO]: "Teemo",
  [Champion.THRESH]: "Thresh",
  [Champion.TRISTANA]: "Tristana",
  [Champion.TRUNDLE]: "Trundle",
  [Champion.TRYNDAMERE]: "Tryndamere",
  [Champion.TWISTEDFATE]: "Twisted Fate",
  [Champion.TWITCH]: "Twitch",
  [Champion.UDYR]: "Udyr",
  [Champion.URGOT]: "Urgot",
  [Champion.VARUS]: "Varus",
  [Champion.VAYNE]: "Vayne",
  [Champion.VEIGAR]: "Veigar",
  [Champion.VELKOZ]: "Vel'Koz",
  [Champion.VEX]: "Vex",
  [Champion.VI]: "Vi",
  [Champion.VIEGO]: "Viego",
  [Champion.VIKTOR]: "Viktor",
  [Champion.VLADIMIR]: "Vladimir",
  [Champion.VOLIBEAR]: "Volibear",
  [Champion.WARWICK]: "Warwick",
  [Champion.XAYAH]: "Xayah",
  [Champion.XERATH]: "Xerath",
  [Champion.XINZHAO]: "Xin Zhao",
  [Champion.YASUO]: "Yasuo",
  [Champion.YONE]: "Yone",
  [Champion.YORICK]: "Yorick",
  [Champion.YUUMI]: "Yuumi",
  [Champion.ZAC]: "Zac",
  [Champion.ZED]: "Zed",
  [Champion.ZERI]: "Zeri",
  [Champion.ZIGGS]: "Ziggs",
  [Champion.ZILEAN]: "Zilean",
  [Champion.ZOE]: "Zoe",
  [Champion.ZYRA]: "Zyra",
};
